on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    

    steps:
    #checkout the repository to GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    #Login to Azure via Azure CLI
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #Install the latest version of the Terraform CLI
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    #Initialize a new or existing Terraform working directory
    # Creating initial files, loading any remote state, and downloading any modules, etc.
    - name: Initialize Terraform
      run: terraform init

    #Generate an execution plan for Terraform
    - name: Terraform plan
      id: plan
      run: terraform plan -input=false -out=plan.tfplan -var-file="terraform.tfvars"

    #Save plan to artifacts
    - name: Save plan
      uses: actions/upload-artifact@v4
      with:
        name: plan.tfplan
        path: plan.tfplan

  terraform-apply:
    name: Terraform apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
    #checkout the repository to GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    #Install the latest version of the Terraform CLI
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    #Initialize a new or existing Terraform working directory
    # Creating initial files, loading any remote state, and downloading any modules, etc.
    - name: Initialize Terraform
      run: terraform init

    #Download saved plan from artifacts
    - name: Download plan
      uses: actions/download-artifact@v3
      with:
        name: plan.tfplan
        path: plan.tfplan

    #Terraform apply
    - name: Terraform apply
      run: terraform apply -var-file="values.tfvars" -auto-approve tfplan 
